//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ExpertScience
    {
        public int id { get; set; }
        public string expertid { get; set; }
        public string ins1_cls1 { get; set; }
        public string ins1_cls2 { get; set; }
        public string ins1_cls3 { get; set; }
        public string ins2_cls1 { get; set; }
        public string ins2_cls2 { get; set; }
        public string ins2_cls3 { get; set; }
        public string ins3_cls1 { get; set; }
        public string ins3_cls2 { get; set; }
        public string ins3_cls3 { get; set; }
        public string dom1_cls1 { get; set; }
        public string dom1_cls2 { get; set; }
        public string dom1_cls3 { get; set; }
        public string dom2_cls1 { get; set; }
        public string dom2_cls2 { get; set; }
        public string dom2_cls3 { get; set; }
        public string dom3_cls1 { get; set; }
        public string dom3_cls2 { get; set; }
        public string dom3_cls3 { get; set; }
        public Nullable<int> side_yj { get; set; }
        public Nullable<int> side_rj { get; set; }
        public Nullable<int> side_yy { get; set; }
        public Nullable<int> side_cz { get; set; }
        public Nullable<int> side_sjcl { get; set; }
        public Nullable<int> side_scfx { get; set; }
        public Nullable<int> side_qt { get; set; }
        public string side_qt_des { get; set; }
        public Nullable<int> language { get; set; }
        public Nullable<int> languagelevel { get; set; }
        public Nullable<int> itlevel { get; set; }
        public Nullable<int> training { get; set; }
        public Nullable<int> firm_familiarity { get; set; }
        public Nullable<int> gov_familiarity { get; set; }
    }
}
