//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_Comment
    {
        public int id { get; set; }
        public string expertid { get; set; }
        public Nullable<int> publicity { get; set; }
        public Nullable<int> familiarity { get; set; }
        public Nullable<int> character { get; set; }
        public Nullable<int> mandarinlevel { get; set; }
        public Nullable<int> tickling { get; set; }
        public Nullable<int> cooperative1 { get; set; }
        public Nullable<int> cooperative2 { get; set; }
        public Nullable<short> works_zlfy { get; set; }
        public Nullable<short> works_zxgj { get; set; }
        public Nullable<short> works_pxzj { get; set; }
        public Nullable<short> works_hdjb { get; set; }
        public Nullable<short> works_zx { get; set; }
        public Nullable<short> works_qt { get; set; }
        public string recommend { get; set; }
    }
}
