//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_Records
    {
        public int ID { get; set; }
        public string expertid { get; set; }
        public Nullable<int> progromid { get; set; }
        public Nullable<int> actionid { get; set; }
        public string actiontitle { get; set; }
        public Nullable<System.DateTime> actionstartdate { get; set; }
        public Nullable<System.DateTime> actionenddate { get; set; }
        public string inviter { get; set; }
        public string follow { get; set; }
        public Nullable<decimal> reward { get; set; }
        public Nullable<decimal> income { get; set; }
        public Nullable<int> tickling { get; set; }
    }
}
