//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_Expert
    {
        public int id { get; set; }
        public string name { get; set; }
        public string vipaccount { get; set; }
        public Nullable<short> sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<int> province { get; set; }
        public Nullable<int> city { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public string officephone { get; set; }
        public string mobilephone { get; set; }
        public string homephone { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public Nullable<short> exptype { get; set; }
        public Nullable<short> education { get; set; }
        public Nullable<short> jobtitle { get; set; }
        public Nullable<short> jobposition { get; set; }
        public Nullable<short> jobstatus { get; set; }
        public string unitname { get; set; }
        public Nullable<short> sparetime { get; set; }
        public string hobbies { get; set; }
        public string resumeurl { get; set; }
        public string remark { get; set; }
        public byte[] rowversion { get; set; }
        public string positions1 { get; set; }
        public string positions2 { get; set; }
        public string positions3 { get; set; }
        public string expertid { get; set; }
    }
}
