//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_Admin_User
    {
        public int id { get; set; }
        public string admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_password { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string MobileCode { get; set; }
        public Nullable<System.DateTime> MobileCodeTime { get; set; }
        public string MSN { get; set; }
        public string TQ { get; set; }
        public string item { get; set; }
        public short ISExpert { get; set; }
        public string DPID { get; set; }
        public string admin_email { get; set; }
        public string PMID { get; set; }
        public string InnerBBS { get; set; }
        public string TLID { get; set; }
        public string IMMSortID { get; set; }
        public string IMType { get; set; }
        public long Score_Total { get; set; }
        public int Score_Month { get; set; }
        public string CCU_ID { get; set; }
        public string Paper { get; set; }
        public string EDM { get; set; }
        public System.DateTime LastModifyPasswordTime { get; set; }
        public string VipManagerType { get; set; }
        public string ExpertManagerType { get; set; }
        public string RwzfManagerType { get; set; }
        public string ItemID { get; set; }
        public bool IS_Pass { get; set; }
        public short News_ManagerType { get; set; }
        public string News_ManagerList { get; set; }
        public string AdManager { get; set; }
        public string WPToWhoID { get; set; }
        public string VIPname { get; set; }
        public string StaffList { get; set; }
        public bool zc_manager { get; set; }
        public bool zc_principal { get; set; }
        public string SRT_ID { get; set; }
        public Nullable<short> CRMType { get; set; }
        public string IM_Column { get; set; }
        public string SiteID { get; set; }
        public string MenuID { get; set; }
        public Nullable<int> COMBehaviorManager { get; set; }
        public int ApplicationManager { get; set; }
        public int ConsumablesManager { get; set; }
        public Nullable<int> EDMManager { get; set; }
        public Nullable<int> mobileManager { get; set; }
        public int travelreport { get; set; }
        public string QQ { get; set; }
        public string searchManager { get; set; }
        public string OpenID_WX { get; set; }
        public string SensitiveWordType { get; set; }
        public string WT_ClassID { get; set; }
        public Nullable<int> CustomersNum { get; set; }
        public int IsAdmin { get; set; }
        public string SRTID { get; set; }
        public int NTLID { get; set; }
        public int ParentDpid { get; set; }
        public int SubDpid { get; set; }
        public int FlauntManager { get; set; }
        public int QualificationManager { get; set; }
        public int isopennew { get; set; }
    }
}
