//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_SortMain
    {
        public short ID { get; set; }
        public string IMMSortID { get; set; }
        public string IMMSortName { get; set; }
        public short IMMSortOrder { get; set; }
        public string IMDomain { get; set; }
        public string EnName { get; set; }
    }
}
