//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_Sort
    {
        public int ID { get; set; }
        public string IMType { get; set; }
        public string IMNote { get; set; }
        public string IMMSortID { get; set; }
        public int IMOrder { get; set; }
        public string IMSort { get; set; }
        public string IMDomain { get; set; }
        public string IMTitle { get; set; }
        public string IMKeywords { get; set; }
        public string IMDescription { get; set; }
        public bool DisplayInNetShow { get; set; }
        public string CustomizeSortIndex { get; set; }
        public string SortTag { get; set; }
        public int ClassID { get; set; }
        public Nullable<long> ConsumablesCount { get; set; }
        public string ADLocationIDList { get; set; }
        public Nullable<int> ForumID { get; set; }
        public string Summary { get; set; }
        public string EnName { get; set; }
    }
}
