//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_SortClass
    {
        public int ID { get; set; }
        public string IMSortType { get; set; }
        public string IMType { get; set; }
        public string IMNote { get; set; }
        public byte ISZC { get; set; }
        public string NameID { get; set; }
        public long visitcount { get; set; }
        public long visitcount_month { get; set; }
        public long GBookNum { get; set; }
        public long GBookNum_Month { get; set; }
        public string keywords { get; set; }
        public Nullable<System.DateTime> Date_ZC { get; set; }
        public string RelatedSearch_Name1 { get; set; }
        public string RelatedSearch_URL1 { get; set; }
        public string RelatedSearch_Name2 { get; set; }
        public string RelatedSearch_URL2 { get; set; }
        public string RelatedSearch_Name3 { get; set; }
        public string RelatedSearch_URL3 { get; set; }
        public int IMOrder { get; set; }
        public long maxIMShowBRank { get; set; }
        public int DisplayNewproductPromotion { get; set; }
        public short setDisplayResult { get; set; }
        public bool ISWrap { get; set; }
        public Nullable<int> IMSHowBCount { get; set; }
        public Nullable<int> IMSHowIDCount { get; set; }
        public bool IsChangeColor { get; set; }
        public string Meta_Title { get; set; }
        public string Meta_Keywords { get; set; }
        public string Meta_Description { get; set; }
        public bool showIndex { get; set; }
        public long productCount { get; set; }
        public Nullable<long> ConsumablesCount { get; set; }
        public string zc_chengshudu { get; set; }
        public string Summary { get; set; }
        public int IMLevel { get; set; }
        public string EnName { get; set; }
    }
}
