//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace instrument.expert.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample_Sort
    {
        public string Sample_SortID { get; set; }
        public string Sample_SortName { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> ISshow { get; set; }
        public Nullable<bool> IsShowIndex { get; set; }
    }
}
